version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-env-newrelic: &env-newrelic
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-mongo: &env-mongo
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
  ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}

x-env-elastic: &env-elastic
  ELASTICSEARCH_URL: ${ELASTICSEARCH_URL-http://elasticsearch:9200}

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /base-cms
  volumes:
    - .:/base-cms:cached
    - ./node_modules:/base-cms/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /base-cms
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "10000:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      server.name: kibana
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL-http://elasticsearch:9200}"
      LOGGING_QUIET: "true"
    depends_on:
      - elasticsearch
    ports:
      - "10001:5601"

  keyword-analysis:
    << : *node
    working_dir: /base-cms/services/keyword-analysis
    command: ["src"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      <<: *env-elastic
    depends_on:
      - mongodb
      - elasticsearch
      - kibana

  # GRAPHQL

  graphql-server:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      PORT: 80
      EXPOSED_PORT: 10002
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "10002:80"

  graphql-server-aerilon:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      MONGO_DSN: ${MONGO_DSN_AERILON-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      PORT: 80
      EXPOSED_PORT: 11000
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11000:80"

  graphql-server-caprica:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      MONGO_DSN: ${MONGO_DSN_CAPRICA-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      PORT: 80
      EXPOSED_PORT: 11001
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11001:80"

  graphql-server-picon:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      MONGO_DSN: ${MONGO_DSN_PICON-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      PORT: 80
      EXPOSED_PORT: 11002
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11002:80"

  graphql-server-gemenon:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      MONGO_DSN: ${MONGO_DSN_GEMENON-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      PORT: 80
      EXPOSED_PORT: 11008
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11008:80"

  # RSS

  rss:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10011
    depends_on:
      - graphql-server
    ports:
      - "10011:80"

  rss-aerilon:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-aerilon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11002
    depends_on:
      - graphql-server-aerilon
    ports:
      - "11002:80"

  rss-caprica:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-caprica
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11003
    depends_on:
      - graphql-server-caprica
    ports:
      - "11003:80"

  rss-picon:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-picon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11004
    depends_on:
      - graphql-server-picon
    ports:
      - "11004:80"

  rss-gemenon:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-gemenon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11009
    depends_on:
      - graphql-server-gemenon
    ports:
      - "11009:80"

  # SITEMAPS

  sitemaps:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10009
    depends_on:
      - graphql-server
    ports:
      - "10009:80"

  sitemaps-aerilon:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-aerilon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11005
    depends_on:
      - graphql-server-aerilon
    ports:
      - "11005:80"

  sitemaps-caprica:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-caprica
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11006
    depends_on:
      - graphql-server-caprica
    ports:
      - "11006:80"

  sitemaps-picon:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-picon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11007
    depends_on:
      - graphql-server-picon
    ports:
      - "11007:80"

  sitemaps-gemenon:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-gemenon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11010
    depends_on:
      - graphql-server-gemenon
    ports:
      - "11010:80"

  # EXAMPLES

  example-newsletters-ien:
    <<: *node
    working_dir: /base-cms/services/example-newsletters-ien
    command: ["/base-cms/node_modules/.bin/basecms-newsletters", "dev", "index.js"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 11090
      LIVERELOAD_PORT: 21090
      TENANT_KEY: indm_ien
      GRAPHQL_URI: http://graphql-server-caprica
      NEW_RELIC_ENABLED: 0
      NEW_RELIC_LICENSE_KEY: (unset)
    depends_on:
      - graphql-server-caprica
    ports:
      - "11090:80"
      - "21090:21090"

  example-website-lfw:
    <<: *node
    working_dir: /base-cms/services/example-website-lfw
    command: ["/base-cms/node_modules/.bin/basecms-website", "dev", "index.js"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 11162
      LIVERELOAD_PORT: 25162
      TENANT_KEY: ebm_lfw
      SITE_ID: 5ca4e38775a25490050041a7
      GRAPHQL_URI: http://graphql-server-aerilon
      SITEMAPS_URI: http://sitemaps-aerilon
      RSS_URI: http://rss-aerilon
      OEMBED_URI: http://oembed
      NEW_RELIC_ENABLED: 0
      NEW_RELIC_LICENSE_KEY: (unset)
    depends_on:
      - graphql-server-aerilon
      - sitemaps-aerilon
      - rss-aerilon
      - oembed
    ports:
      - "11162:80"
      - "25162:25162"

  example-website-bzb:
    <<: *node
    working_dir: /base-cms/services/example-website-bzb
    command: ["/base-cms/node_modules/.bin/basecms-website", "dev", "index.js"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 11163
      LIVERELOAD_PORT: 25163
      TENANT_KEY: bizbash_bzb
      SITE_ID: 5b295afea1c1c62c008b4572
      GRAPHQL_URI: http://graphql-server-caprica
      SITEMAPS_URI: http://sitemaps-caprica
      RSS_URI: http://rss-caprica
      OEMBED_URI: http://oembed
      NEW_RELIC_ENABLED: 0
      NEW_RELIC_LICENSE_KEY: (unset)
    depends_on:
      - graphql-server-caprica
      - sitemaps-caprica
      - rss-caprica
      - oembed
    ports:
      - "11163:80"
      - "25163:25163"

  example-leaders-program:
    << : *node
    working_dir: /base-cms/packages/leaders-program
    entrypoint: ["/base-cms/node_modules/.bin/vue-cli-service"]
    command: ["serve", "src/dev.js", "--port", "11164"]
    environment:
      <<: *env
    ports:
      - "11164:11164"

  example-website-vspc:
    <<: *node
    working_dir: /base-cms/services/example-website-vspc
    command: ["/base-cms/node_modules/.bin/basecms-website", "dev", "index.js"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 11165
      LIVERELOAD_PORT: 25165
      TENANT_KEY: cygnus_vspc
      SITE_ID: 578631623bab465e7f4932d8
      GRAPHQL_URI: http://graphql-server-picon
      SITEMAPS_URI: http://sitemaps-picon
      RSS_URI: http://rss-picon
      OEMBED_URI: http://oembed
      NEW_RELIC_ENABLED: 0
      NEW_RELIC_LICENSE_KEY: (unset)
    depends_on:
      - graphql-server-picon
      - sitemaps-picon
      - rss-picon
      - oembed
    ports:
      - "11165:80"
      - "25165:25165"

  example-website-iw:
    <<: *node
    working_dir: /base-cms/services/example-website-iw
    command: ["/base-cms/node_modules/.bin/basecms-website", "dev", "index.js"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 11165
      LIVERELOAD_PORT: 25165
      TENANT_KEY: ebm_industryweek
      SITE_ID: 5dc2e4b9a6e839f2008b4567
      GRAPHQL_URI: http://graphql-server-gemenon
      SITEMAPS_URI: http://sitemaps-gemenon
      RSS_URI: http://rss-gemenon
      OEMBED_URI: http://oembed
      NEW_RELIC_ENABLED: 0
      NEW_RELIC_LICENSE_KEY: (unset)
    depends_on:
      - graphql-server-gemenon
      - sitemaps-gemenon
      - rss-gemenon
      - oembed
    ports:
      - "11165:80"
      - "25165:25165"

  haproxy:
    image: haproxy:alpine
    ports: [ "${PORT-10010}:80" ]
    volumes:
      - ./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - example-website-lfw
      - graphql-server

  hooks:
    << : *node
    working_dir: /base-cms/services/hooks
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      CAPRICA_DSN: ${CAPRICA_DSN-mongodb://mongodb:27017}
      AERILON_DSN: ${AERILON_DSN-mongodb://mongodb:27017}
      PICON_DSN: ${PICON_DSN-mongodb://mongodb:27017}
    depends_on:
      - mongodb
    ports:
      - "10012:80"

  oembed:
    << : *node
    working_dir: /base-cms/services/oembed
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      EMBEDLY_API_KEY: ${EMBEDLY_API_KEY}
    ports:
      - "10013:80"

  google-data-api:
    << : *node
    working_dir: /base-cms/services/google-data-api
    entrypoint: ["node_modules/.bin/micro-dev"]
    command: ["--port", "80", "--silent", "--ignore=newrelic"]
    environment:
      <<: *env
      <<: *env-newrelic
      GOOGLE_DATA_MONGO_DSN: ${GOOGLE_DATA_MONGO_DSN-mongodb://mongodb}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - mongodb
    ports:
      - "10014:80"

volumes:
  esdata: {}
  mongodb: {}
  yarn-cache: {}
